apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pdd
  template:
    metadata:
      labels:
        app: pdd
    spec:
      containers:
      - name: appdeploy
        image: raichu08/myapp:v3
        ports:
        - containerPort: 80
